### PR TITLE
FAN-912 adding key for fandom footer

### PR DESCRIPTION
**Pull request by lizlux**
The fandom footer will contain copyright info, not a licensing description. 

One question I have is: what is the process for getting strings inside this repo translated? 

@Wikia/x-wing

### CODE REVIEW

**Comment by lizlux** [comment]
@mklucsarits we'll have to deal with the fact that the design system i18n system uses `__variable__` instead of `printf` like fandom currently uses. Maybe for now it's a one-off hack? Or maybe we create a different function other than `__win()` to handle design system strings...

**Comment by kvas-damian** [comment]
@lizlux maybe you could try with the approach that we used in MW: https://github.com/Wikia/app/blob/dev/extensions/wikia/DesignSystem/i18n/build.js

**Comment by mklucsarits** [comment]
LGTM

**Comment by rogatty** [comment]
LGTM

**Comment by lizlux** [comment]
Found the info for uploading translations here https://wikia-inc.atlassian.net/wiki/display/INT/i18n+tools. Same process as always, just haven't done this in a while! ;)

**Pull request merged**
